_includes/binarization/activities/binarization.py
_includes/binarization/activities/binarization_imagejmacro.md
_includes/binarization/activities/binarization_jython.md
_includes/binarization/activities/binarization_matlab.md
_layouts/module.html
_modules/binarization.md

Closes #57 
Closes #55 
Closes #23 
This makes the changes to the module template as discussed previously.
- #55 : you now have a separate _Assessment_ section at the end, which is for a generic assessment of understanding of the central concept in the module. `exercises_preface` has been removed and replaced by `assessment`.
- #57 : the `activities` field in the YAML of a module file is now a "list of lists," with each entry containing three items: the name of the platform (e.g. `"ImageJ Macro"`), the path to the activity file/script (e.g. `"/binarization/activities/binarization.py"`), and a language name for syntax highlighting (e.g. `"python"`).
- activity instructions that should not be displayed as code blocks should be provided with the language identifier "markdown" for their …

Template Adjustments

---

CONTRIBUTING.md

closes #56 
Please check that what I've written here makes sense.

update contributing guide to match latest template

---

_includes/spatial_calibration/activities/spatial_calibration_imagejgui.md
_modules/measure_intensities.md
_modules/spatial_calibration.md

Did you already merge the previous PR?
I could not see it anymore...
Anyway, here are some further improvements, I hope.

Improve spatial calibration exercises

---

_includes/pixels/activities/pixels2D_matlab.m
_modules/pixels.md

added MATLAB implementation for pixels module
1. modified `pixels.md` in `_modules`
2. added `pixels2D_matlab.m` in `_includes/pixels/activities`
I hope everything makes sense!
Thank you,
Stefania

add MATLAB implementation for module pixels

---

_modules/commenting.md

WIP commenting module pull request

WIP: commenting module

---

_includes/output_saving/activities/output_saving_jython.py
_includes/output_saving/activities/output_saving_macro.ijm
_includes/output_saving/exercises/output_saving_imagejmacro.md
_includes/output_saving/exercises/output_saving_jython.md
_modules/output_saving.md

I have made changes to the output_saving module such that the user has to specify a path by changing 
`outputDir = FIXME` to specify a path on their computer.

updates for specifying an output directory and camelCase

---

_includes/all-modules.md
_modules/commenting.md
_modules/filter_neighbourhood.md
_modules/filter_objects.md
_modules/lut.md
_modules/output_saving.md
_modules/script_functions.md
_modules/script_run.md
_modules/string_concat.md
_modules/variables.md
_modules/workflow_segment_2d_noisy_nuclei_filter_objects_measure_shape.md
_modules/workflow_segment_2d_nuclei_measure_shape.md

@manerotoni 
I managed to introduce module tagging. Should be super useful, I think :)

Introduce and use tags

---

_includes/volume_slicing/exercises/volume_slicing_gui.md
_modules/volume_slicing.md

To fix issue  #241 and #239 
I still have to think about the assessments.

updated module name and added answer that was missing in the exercise

---

_modules/volume_slicing.md

Sorry, found a typo that made the image path show up incorrectly. Could you merge again? Thanks!

fixed typo in the file path to image data

---

_includes/local_background_correction/activities/local_background_correction_activity2_gui.md

@tischi This should fix the indentation issue in the activity. If you agree with the new version, can you please merge? Thanks!

updated the indentation in the activity

---

_includes/measure_shapes/activities/measure_shapes_imagejgui.md
_modules/measure_shapes.md

Measure shapes

---

_modules/measure_intensities.md

Have look just minor changes. Can be merged.

minor change on concept map. Better agreement with measure_shapes layout

---

_includes/watershed/exercises/morpholibj_seeded_watershed_exercise.ijm
_includes/watershed/exercises/morpholibj_shape_watershed_exercise.ijm

@tischi 
this is with syntax highlight. You can now copy paste the exercise solution.

syntax highlight

---

_includes/local_background_correction/activities/local_background_correction_imagejgui.md

@tischi @manerotoni ,
I found a small typo in the link to the image in the local background correction module, activity 1. I corrected it and if alright with you I will directly merge with master so that it is fixed before the course today.

updated link to figure in activity 1

---

_includes/auto_threshold/exercises/auto_threshold_imagejgui.md
_modules/auto_threshold.md

corrected wrt Toni

---

courses/2023_skimage_napari_beginners.md

not sure what a multiactivity is, but yeah :D

Added myself to some todos

---

_includes/spatial_calibration/activities/spatial_calibration_skimage_napari.py

Done reading and writing tif file from the script.
Until wrapper function is implemented.

created spatial calibration activity

---

_includes/filter_morphological/activities/filter_morphological_skimage_napari.py
_modules/filter_morphological.md

@grinic I rebased your branch `python_morphological_filters` with `git rebase -i origin/master` and then moved it to this branch with `git checkout -b python_morphological_filters_rebased`.
It looks like this branch contains now only the changes we want to merge.

Python morphological filters rebased

---

_includes/lut/lut_act1.md
_includes/lut/lut_act1_skimage_napari.py
_includes/lut/lut_act2.md
_includes/lut/lut_act2_skimage_napari.py

Clean up activities
Add decorators for cells in jupyter
Naming consistency

LUT module

---

_includes/auto_threshold/auto_threshold_act1.md
_includes/auto_threshold/auto_threshold_act1_skimage_napari.py
_includes/auto_threshold/auto_threshold_act2.md
_includes/auto_threshold/auto_threshold_act2_skimage_napari.py

Verified the module. Fix error in activity 2. 
Add scales for 3D rendering.
Add links to activities

Automatic thresholding verify

---

_includes/multidimensional_images/multidimensional_images_act1_skimage_napari.py
_includes/multidimensional_images/multidimensional_images_act2_skimage_napari.py
_includes/multidimensional_images/multidimensional_images_act3_skimage_napari.py
_includes/multidimensional_images/multidimensional_images_act4.md
_includes/multidimensional_images/multidimensional_images_act4_imagejgui.md
_includes/multidimensional_images/multidimensional_images_act4_napari.md
_includes/multidimensional_images/multidimensional_images_act4_skimage_napari.py

Hi,
@grinic @manerotoni @tibuch @AnniekStok 
I am looking at this module, as I will have to teach it :-)
First question: should I also teach the drag&drop pure Napari activity? Or only the skimage one? I would prefer to only do the skimage implementation.

Review multi-dimensional images

---

_includes/workflow_segment_2d_nuclei_measure_shape/segment_2d_nuclei.md
_includes/workflow_segment_2d_nuclei_measure_shape/segment_2d_nuclei_skimage_napari.py

I fixed the issues in the activity. 
I also added more learning opportunities. 
The for loop, and how to save the data, came during the hands on.
It could be merged straight away.

fix naming, more learning opportunities

---

_includes/local_background_correction/local_background_correction_act2_skimage_napari.py

Python local background correction

---

courses/2024_volumetric_image_inspection_and_presentation.md

or should the text here be more informative/directed towards student?

Some minimal information and links for the blender part of the course

---

_includes/median_filter/median_filter_skimage_napari.py

I need to teach this tomorrow, thus please comment today; sorry for the rush.

Improve median_filter_skimage_napari.py

---

_includes/coding_with_llms/code_creation_chatGPT_python.md

Hey @tischi 
Great course! So it doesn't get forgotten, here's a quick fix PR for the Chat-GPT link in the Coding with LLMs section

Fix Chat-GPT link

---

_includes/batch_processing/batch_measure_nuclei_shape.py
_includes/batch_processing/batch_measure_nuclei_shapes.md

I've updated the batch processing module:
1. save_ij_tiff instead of imsave
2. Open the first image and resulting segmentation in the end to illustrate that the workflow was working
3. Added the suggestion to first only build an empty analyse function and run it to make sure this works before filling in functionality
4. Changed the variable name of the input directory outside of the function
Regarding 3., I'm not sure if  [this](https://github.com/NEUBIAS/training-resources/blob/batch_processing/_includes/batch_processing/batch_measure_nuclei_shapes.md) is understandable, any suggestions are welcome.

Updates for batch processing
